#
# GENERATED by scripts/Build-ScoutServiceCollector.ps1 from manifests/specs/service-collectors.psd1 (AB#6741).
# Authored as data -- there is no source collector script to drift from. Edit the spec and
# regenerate; do not hand-patch this file.
#
@{
    ResourceTypes = @(
        'AZSC/VM/Quotas'
    )

    ResourceTypeMatching = 'Grouped'

    AdditionalFilter = $null

    FilterPreamble = ''

    RowLoopVariable = '1'

    Preamble = @'
$ResUCount = 1
                $data = $1.PROPERTIES
'@

    AdditionalRowLoops = @(
        @{
            Variable = 'Loc'
            Source = '$data'
            Preamble = ''
        }
        @{
            Variable = 'Usage'
            Source = '$Loc.Data'
            Preamble = ''
        }
    )

    TagLoop = $null

    Fields = @(
        @{
            Name = 'ID'
            Expression = '$Loc.SubId'
        }
        @{
            Name = 'Subscription'
            Expression = '$Loc.Subscription'
        }
        @{
            Name = 'Location'
            Expression = '$Loc.Location'
        }
        @{
            Name = 'Quota'
            Expression = '$Usage.Name.LocalizedValue'
        }
        @{
            Name = 'Quota Name'
            Expression = '$Usage.Name.Value'
        }
        @{
            Name = 'Current Value'
            Expression = '[string]$Usage.CurrentValue'
        }
        @{
            Name = 'Limit'
            Expression = '[string]$Usage.Limit'
        }
        @{
            Name = 'Used %'
            Expression = '[string]$(if($null -ne $Usage -and $Usage.Limit -and [double]$Usage.Limit -gt 0){[math]::Round((([double]$Usage.CurrentValue / [double]$Usage.Limit) * 100), 1)}else{$null})'
        }
        @{
            Name = 'Unit'
            Expression = '$Usage.Unit'
        }
        @{
            Name = 'Resource U'
            Expression = '$ResUCount'
        }
    )

    Export = @{
        WorksheetName = 'Quotas'
        TableNamePrefix = 'QuotasTable_'
        Columns = @(
            'Subscription'
            'Location'
            'Quota'
            'Quota Name'
            'Current Value'
            'Limit'
            'Used %'
            'Unit'
            'Resource U'
        )
        TagColumns = @()
        NumberFormat = '0'
        ConditionalText = @()
    }
}
